-- =====================================================================
-- 02b_expand_tickers.sql
-- Extends Companies to ~140 NSE symbols so DailyPrices clears 250k rows,
-- which is the threshold where the Phase 6 index demo becomes visible.
--
-- Run AFTER 02_seed_data.sql, then re-run the loader:
--     python ingest_and_indicators.py --years 10
--
-- INSERT IGNORE means the ten tickers already seeded are skipped rather
-- than raising a duplicate-key error on uq_companies_ticker.
-- =====================================================================

USE stockdb;

-- ---------------------------------------------------------------------
-- Nifty 50 constituents (as of the December 2025 rebalance)
-- ---------------------------------------------------------------------
INSERT IGNORE INTO Companies (ticker, company_name, sector, exchange, currency) VALUES
('ADANIENT',  'Adani Enterprises Ltd',           'Metals & Mining',    'NSE','INR'),
('ADANIPORTS','Adani Ports & SEZ Ltd',           'Services',           'NSE','INR'),
('APOLLOHOSP','Apollo Hospitals Enterprise Ltd', 'Healthcare',         'NSE','INR'),
('ASIANPAINT','Asian Paints Ltd',                'Consumer Durables',  'NSE','INR'),
('AXISBANK',  'Axis Bank Ltd',                   'Financial Services', 'NSE','INR'),
('BAJAJ-AUTO','Bajaj Auto Ltd',                  'Automobile',         'NSE','INR'),
('BAJFINANCE','Bajaj Finance Ltd',               'Financial Services', 'NSE','INR'),
('BAJAJFINSV','Bajaj Finserv Ltd',               'Financial Services', 'NSE','INR'),
('BEL',       'Bharat Electronics Ltd',          'Capital Goods',      'NSE','INR'),
('BHARTIARTL','Bharti Airtel Ltd',               'Telecommunication',  'NSE','INR'),
('CIPLA',     'Cipla Ltd',                       'Healthcare',         'NSE','INR'),
('COALINDIA', 'Coal India Ltd',                  'Oil Gas & Fuels',    'NSE','INR'),
('DRREDDY',   'Dr Reddys Laboratories Ltd',      'Healthcare',         'NSE','INR'),
('EICHERMOT', 'Eicher Motors Ltd',               'Automobile',         'NSE','INR'),
('ETERNAL',   'Eternal Ltd',                     'Consumer Services',  'NSE','INR'),
('GRASIM',    'Grasim Industries Ltd',           'Construction Mat',   'NSE','INR'),
('HCLTECH',   'HCL Technologies Ltd',            'Information Tech',   'NSE','INR'),
('HDFCLIFE',  'HDFC Life Insurance Co Ltd',      'Financial Services', 'NSE','INR'),
('HINDALCO',  'Hindalco Industries Ltd',         'Metals & Mining',    'NSE','INR'),
('HINDUNILVR','Hindustan Unilever Ltd',          'Consumer Goods',     'NSE','INR'),
('ICICIBANK', 'ICICI Bank Ltd',                  'Financial Services', 'NSE','INR'),
('INDIGO',    'InterGlobe Aviation Ltd',         'Services',           'NSE','INR'),
('JIOFIN',    'Jio Financial Services Ltd',      'Financial Services', 'NSE','INR'),
('JSWSTEEL',  'JSW Steel Ltd',                   'Metals & Mining',    'NSE','INR'),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd',         'Financial Services', 'NSE','INR'),
('M&M',       'Mahindra & Mahindra Ltd',         'Automobile',         'NSE','INR'),
('MAXHEALTH', 'Max Healthcare Institute Ltd',    'Healthcare',         'NSE','INR'),
('NESTLEIND', 'Nestle India Ltd',                'Consumer Goods',     'NSE','INR'),
('NTPC',      'NTPC Ltd',                        'Power',              'NSE','INR'),
('ONGC',      'Oil & Natural Gas Corp Ltd',      'Oil Gas & Fuels',    'NSE','INR'),
('POWERGRID', 'Power Grid Corp of India Ltd',    'Power',              'NSE','INR'),
('SBILIFE',   'SBI Life Insurance Co Ltd',       'Financial Services', 'NSE','INR'),
('SHRIRAMFIN','Shriram Finance Ltd',             'Financial Services', 'NSE','INR'),
('TATACONSUM','Tata Consumer Products Ltd',      'Consumer Goods',     'NSE','INR'),
('TATAMOTORS','Tata Motors Ltd',                 'Automobile',         'NSE','INR'),
('TMPV',      'Tata Motors Passenger Vehicles',  'Automobile',         'NSE','INR'),
('TATASTEEL', 'Tata Steel Ltd',                  'Metals & Mining',    'NSE','INR'),
('TECHM',     'Tech Mahindra Ltd',               'Information Tech',   'NSE','INR'),
('TITAN',     'Titan Company Ltd',               'Consumer Durables',  'NSE','INR'),
('TRENT',     'Trent Ltd',                       'Consumer Services',  'NSE','INR'),
('ULTRACEMCO','UltraTech Cement Ltd',            'Construction Mat',   'NSE','INR');


-- ---------------------------------------------------------------------
-- Additional NSE large and mid caps with long listing histories
-- ---------------------------------------------------------------------
INSERT IGNORE INTO Companies (ticker, company_name, sector, exchange, currency) VALUES
('ABB',       'ABB India Ltd',                   'Capital Goods',      'NSE','INR'),
('ABBOTINDIA','Abbott India Ltd',                'Healthcare',         'NSE','INR'),
('ACC',       'ACC Ltd',                         'Construction Mat',   'NSE','INR'),
('ALKEM',     'Alkem Laboratories Ltd',          'Healthcare',         'NSE','INR'),
('AMBUJACEM', 'Ambuja Cements Ltd',              'Construction Mat',   'NSE','INR'),
('APOLLOTYRE','Apollo Tyres Ltd',                'Automobile',         'NSE','INR'),
('ASHOKLEY',  'Ashok Leyland Ltd',               'Automobile',         'NSE','INR'),
('ASTRAL',    'Astral Ltd',                      'Industrial Products','NSE','INR'),
('AUBANK',    'AU Small Finance Bank Ltd',       'Financial Services', 'NSE','INR'),
('AUROPHARMA','Aurobindo Pharma Ltd',            'Healthcare',         'NSE','INR'),
('BALKRISIND','Balkrishna Industries Ltd',       'Automobile',         'NSE','INR'),
('BANKBARODA','Bank of Baroda',                  'Financial Services', 'NSE','INR'),
('BATAINDIA', 'Bata India Ltd',                  'Consumer Durables',  'NSE','INR'),
('BERGEPAINT','Berger Paints India Ltd',         'Consumer Durables',  'NSE','INR'),
('BHARATFORG','Bharat Forge Ltd',                'Automobile',         'NSE','INR'),
('BHEL',      'Bharat Heavy Electricals Ltd',    'Capital Goods',      'NSE','INR'),
('BIOCON',    'Biocon Ltd',                      'Healthcare',         'NSE','INR'),
('BOSCHLTD',  'Bosch Ltd',                       'Automobile',         'NSE','INR'),
('BRITANNIA', 'Britannia Industries Ltd',        'Consumer Goods',     'NSE','INR'),
('CANBK',     'Canara Bank',                     'Financial Services', 'NSE','INR'),
('CHOLAFIN',  'Cholamandalam Investment & Fin',  'Financial Services', 'NSE','INR'),
('COLPAL',    'Colgate Palmolive India Ltd',     'Consumer Goods',     'NSE','INR'),
('CONCOR',    'Container Corp of India Ltd',     'Services',           'NSE','INR'),
('COROMANDEL','Coromandel International Ltd',    'Chemicals',          'NSE','INR'),
('CUMMINSIND','Cummins India Ltd',               'Capital Goods',      'NSE','INR'),
('DABUR',     'Dabur India Ltd',                 'Consumer Goods',     'NSE','INR'),
('DALBHARAT', 'Dalmia Bharat Ltd',               'Construction Mat',   'NSE','INR'),
('DEEPAKNTR', 'Deepak Nitrite Ltd',              'Chemicals',          'NSE','INR'),
('DIVISLAB',  'Divis Laboratories Ltd',          'Healthcare',         'NSE','INR'),
('DLF',       'DLF Ltd',                         'Realty',             'NSE','INR'),
('ESCORTS',   'Escorts Kubota Ltd',              'Capital Goods',      'NSE','INR'),
('EXIDEIND',  'Exide Industries Ltd',            'Automobile',         'NSE','INR'),
('FEDERALBNK','Federal Bank Ltd',                'Financial Services', 'NSE','INR'),
('GAIL',      'GAIL India Ltd',                  'Oil Gas & Fuels',    'NSE','INR'),
('GLENMARK',  'Glenmark Pharmaceuticals Ltd',    'Healthcare',         'NSE','INR'),
('GODREJCP',  'Godrej Consumer Products Ltd',    'Consumer Goods',     'NSE','INR'),
('GODREJPROP','Godrej Properties Ltd',           'Realty',             'NSE','INR'),
('HAVELLS',   'Havells India Ltd',               'Consumer Durables',  'NSE','INR'),
('HEROMOTOCO','Hero MotoCorp Ltd',               'Automobile',         'NSE','INR'),
('HINDPETRO', 'Hindustan Petroleum Corp Ltd',    'Oil Gas & Fuels',    'NSE','INR'),
('IDFCFIRSTB','IDFC First Bank Ltd',             'Financial Services', 'NSE','INR'),
('IEX',       'Indian Energy Exchange Ltd',      'Financial Services', 'NSE','INR'),
('IGL',       'Indraprastha Gas Ltd',            'Oil Gas & Fuels',    'NSE','INR'),
('INDHOTEL',  'Indian Hotels Company Ltd',       'Consumer Services',  'NSE','INR'),
('INDUSINDBK','IndusInd Bank Ltd',               'Financial Services', 'NSE','INR'),
('IOC',       'Indian Oil Corporation Ltd',      'Oil Gas & Fuels',    'NSE','INR'),
('IPCALAB',   'IPCA Laboratories Ltd',           'Healthcare',         'NSE','INR'),
('IRCTC',     'Indian Railway Catering & Tour',  'Consumer Services',  'NSE','INR'),
('JINDALSTEL','Jindal Steel & Power Ltd',        'Metals & Mining',    'NSE','INR'),
('JUBLFOOD',  'Jubilant Foodworks Ltd',          'Consumer Services',  'NSE','INR'),
('LICHSGFIN', 'LIC Housing Finance Ltd',         'Financial Services', 'NSE','INR'),
('LUPIN',     'Lupin Ltd',                       'Healthcare',         'NSE','INR'),
('MARICO',    'Marico Ltd',                      'Consumer Goods',     'NSE','INR'),
('MFSL',      'Max Financial Services Ltd',      'Financial Services', 'NSE','INR'),
('MOTHERSON', 'Samvardhana Motherson Intl Ltd',  'Automobile',         'NSE','INR'),
('MPHASIS',   'Mphasis Ltd',                     'Information Tech',   'NSE','INR'),
('MRF',       'MRF Ltd',                         'Automobile',         'NSE','INR'),
('MUTHOOTFIN','Muthoot Finance Ltd',             'Financial Services', 'NSE','INR'),
('NAUKRI',    'Info Edge India Ltd',             'Consumer Services',  'NSE','INR'),
('NAVINFLUOR','Navin Fluorine International',    'Chemicals',          'NSE','INR'),
('NMDC',      'NMDC Ltd',                        'Metals & Mining',    'NSE','INR'),
('OBEROIRLTY','Oberoi Realty Ltd',               'Realty',             'NSE','INR'),
('OFSS',      'Oracle Financial Services Soft',  'Information Tech',   'NSE','INR'),
('PAGEIND',   'Page Industries Ltd',             'Textiles',           'NSE','INR'),
('PEL',       'Piramal Enterprises Ltd',         'Financial Services', 'NSE','INR'),
('PERSISTENT','Persistent Systems Ltd',          'Information Tech',   'NSE','INR'),
('PETRONET',  'Petronet LNG Ltd',                'Oil Gas & Fuels',    'NSE','INR'),
('PFC',       'Power Finance Corporation Ltd',   'Financial Services', 'NSE','INR'),
('PIDILITIND','Pidilite Industries Ltd',         'Chemicals',          'NSE','INR'),
('PIIND',     'PI Industries Ltd',               'Chemicals',          'NSE','INR'),
('PNB',       'Punjab National Bank',            'Financial Services', 'NSE','INR'),
('POLYCAB',   'Polycab India Ltd',               'Industrial Products','NSE','INR'),
('RECLTD',    'REC Ltd',                         'Financial Services', 'NSE','INR'),
('SAIL',      'Steel Authority of India Ltd',    'Metals & Mining',    'NSE','INR'),
('SIEMENS',   'Siemens Ltd',                     'Capital Goods',      'NSE','INR'),
('SRF',       'SRF Ltd',                         'Chemicals',          'NSE','INR'),
('SUNTV',     'Sun TV Network Ltd',              'Media',              'NSE','INR'),
('SYNGENE',   'Syngene International Ltd',       'Healthcare',         'NSE','INR'),
('TATACHEM',  'Tata Chemicals Ltd',              'Chemicals',          'NSE','INR'),
('TATACOMM',  'Tata Communications Ltd',         'Telecommunication',  'NSE','INR'),
('TATAELXSI', 'Tata Elxsi Ltd',                  'Information Tech',   'NSE','INR'),
('TATAPOWER', 'Tata Power Company Ltd',          'Power',              'NSE','INR'),
('TORNTPHARM','Torrent Pharmaceuticals Ltd',     'Healthcare',         'NSE','INR'),
('TVSMOTOR',  'TVS Motor Company Ltd',           'Automobile',         'NSE','INR'),
('UBL',       'United Breweries Ltd',            'Consumer Goods',     'NSE','INR'),
('UPL',       'UPL Ltd',                         'Chemicals',          'NSE','INR'),
('VEDL',      'Vedanta Ltd',                     'Metals & Mining',    'NSE','INR'),
('VOLTAS',    'Voltas Ltd',                      'Consumer Durables',  'NSE','INR'),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd',          'Healthcare',         'NSE','INR');


SELECT COUNT(*) AS total_tickers FROM Companies;
SELECT sector, COUNT(*) AS n FROM Companies GROUP BY sector ORDER BY n DESC;